name: "Codex Autonomous Code Review"
description: "Run Codex to review a PR and post review comments"
author: "OpenAI Codex"
branding:
  icon: "search"
  color: "blue"

inputs:
  mode:
    description: "Operation mode: 'review' (code review) or 'act' (autonomous editing)"
    required: false
    default: "review"
  openai_api_key:
    description: "OpenAI API key for the selected model provider"
    required: false
  model:
    description: "Model to use (e.g., gpt-5, gpt-4.1-mini)"
    required: false
    default: "gpt-5"
  reasoning_effort:
    description: "Reasoning effort hint: minimal | low | medium | high"
    required: false
    default: "medium"
  debug_level:
    description: "Debug verbosity: 0 (off), 1 (basic), 2 (trace)"
    required: false
    default: "0"
  dry_run:
    description: "If '1', print payloads but do not post comments"
    required: false
    default: "0"
  stream_agent_messages:
    description: "If '1', stream model output to logs"
    required: false
    default: "1"
  fast_model:
    description: "Fast model for deduplication on repeated runs (review mode only)"
    required: false
    default: "gpt-5-mini"
  fast_reasoning_effort:
    description: "Reasoning effort for fast model (review mode only)"
    required: false
    default: "low"
  act_instructions:
    description: "Additional instructions for act mode (autonomous editing)"
    required: false
    default: ""
  codex_python_version:
    description: "Version spec for codex-python on PyPI (e.g., '>=0.2.3')"
    required: false
    default: ""
  extra_pip_args:
    description: "Additional pip arguments (e.g., --index-url)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install codex-python from PyPI
      shell: bash
      run: |
        set -euo pipefail
        python3 -m pip install --upgrade pip
        if [ -n "${{ inputs.codex_python_version }}" ]; then
          python3 -m pip install PyGithub ${{ inputs.extra_pip_args }} "codex-python${{ inputs.codex_python_version }}"
        else
          python3 -m pip install PyGithub ${{ inputs.extra_pip_args }} codex-python
        fi

    - name: Run Codex autonomous review (CLI)
      shell: bash
      env:
        # Tokens
        GITHUB_TOKEN: ${{ github.token }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        # Config
        CODEX_MODE: ${{ inputs.mode }}
        CODEX_MODEL: ${{ inputs.model }}
        CODEX_REASONING_EFFORT: ${{ inputs.reasoning_effort }}
        CODEX_FAST_MODEL: ${{ inputs.fast_model }}
        CODEX_FAST_REASONING_EFFORT: ${{ inputs.fast_reasoning_effort }}
        CODEX_ACT_INSTRUCTIONS: ${{ inputs.act_instructions }}
        DEBUG_CODEREVIEW: ${{ inputs.debug_level }}
        DRY_RUN: ${{ inputs.dry_run }}
        STREAM_AGENT_MESSAGES: ${{ inputs.stream_agent_messages }}
      run: |
        set -euo pipefail
        # Execute the CLI directly; it detects GitHub Actions via env
        PYTHONPATH="${{ github.action_path }}:${PYTHONPATH:-}" \
          python3 -m cli.main
