name: "Codex Code Review & Actor"
description: "Run Codex to review a PR and post review comments"
author: "OpenAI Codex"
branding:
  icon: "search"
  color: "blue"

inputs:
  mode:
    description: "Operation mode: review | act"
    required: false
    default: "review"
  openai_api_key:
    description: "OpenAI API key for the selected model provider"
    required: false
  model:
    description: "Model to use (e.g., gpt-5, gpt-4.1-mini)"
    required: false
    default: "gpt-5.1-codex-max"
  reasoning_effort:
    description: "Reasoning effort: minimal | low | medium | high"
    required: false
    default: "medium"
  web_search_mode:
    description: "Web search mode: disabled | cached | live"
    required: false
    default: "live"
  debug_level:
    description: "Debug verbosity: 0 (off), 1 (basic), 2 (trace)"
    required: false
    default: "1"
  dry_run:
    description: "If '1', print payloads but do not post comments"
    required: false
    default: "0"
  stream_agent_messages:
    description: "If '1', stream model output to logs"
    required: false
    default: "1"
  act_instructions:
    description: "Additional instructions for act mode (autonomous editing)"
    required: false
    default: ""
  additional_prompt:
    description: "Extra reviewer instructions appended to the review prompt (verbatim)"
    required: false
    default: ""
  codex_python_version:
    description: "Version spec for codex-python on PyPI (e.g., '==1.0.0')"
    required: false
    default: "==1.0.1"
  extra_pip_args:
    description: "Additional pip arguments (e.g., --index-url)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        set -euo pipefail
        valid_efforts="minimal low medium high"
        valid_search_modes="disabled cached live"
        contains_word() { case " $1 " in *" $2 "*) return 0;; *) return 1;; esac; }
        codex_version_spec="${{ inputs.codex_python_version }}"
        # Mode
        case "${{ inputs.mode }}" in review|act) :;; *) echo "::error::Invalid mode: ${{ inputs.mode }} (allowed: review|act)"; exit 2;; esac
        # Reasoning efforts
        if ! contains_word "$valid_efforts" "${{ inputs.reasoning_effort }}"; then
          echo "::error::Invalid reasoning_effort: ${{ inputs.reasoning_effort }} (allowed: minimal|low|medium|high)"; exit 2;
        fi
        # Web search mode
        if ! contains_word "$valid_search_modes" "${{ inputs.web_search_mode }}"; then
          echo "::error::Invalid web_search_mode: ${{ inputs.web_search_mode }} (allowed: disabled|cached|live)"; exit 2;
        fi
        # SDK compatibility (this action expects codex-python 1.x API)
        if echo "$codex_version_spec" | grep -Eq '(^|[<>=~! ,])(0\.|2\.)'; then
          echo "::error::Invalid codex_python_version: ${codex_version_spec}. This action requires codex-python >=1.0 <2.0."
          exit 2
        fi
    - name: Install Python dependencies
      shell: bash
      run: |
        set -euo pipefail
        python3 -m pip install --upgrade pip
        if [ -n "${{ inputs.codex_python_version }}" ]; then
          # Pin codex-python first.
          python3 -m pip install ${{ inputs.extra_pip_args }} "codex-python${{ inputs.codex_python_version }}"
        fi
        python3 -m pip install ${{ inputs.extra_pip_args }} -r "${{ github.action_path }}/requirements.txt"

    - name: Run Codex autonomous review (CLI)
      shell: bash
      env:
        # Tokens
        GITHUB_TOKEN: ${{ github.token }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        # Config
        CODEX_MODE: ${{ inputs.mode }}
        CODEX_MODEL: ${{ inputs.model }}
        CODEX_REASONING_EFFORT: ${{ inputs.reasoning_effort }}
        CODEX_WEB_SEARCH_MODE: ${{ inputs.web_search_mode }}
        CODEX_ACT_INSTRUCTIONS: ${{ inputs.act_instructions }}
        CODEX_ADDITIONAL_PROMPT: ${{ inputs.additional_prompt }}
        DEBUG_CODEREVIEW: ${{ inputs.debug_level }}
        DRY_RUN: ${{ inputs.dry_run }}
        STREAM_AGENT_MESSAGES: ${{ inputs.stream_agent_messages }}
      run: |
        set -euo pipefail
        # Execute the CLI directly; it detects GitHub Actions via env
        PYTHONPATH="${{ github.action_path }}:${PYTHONPATH:-}" \
          python3 -m cli.main
