name: Draft Release

on:
  push:
    branches: [main]

permissions:
  contents: write

concurrency:
  group: draft-release
  cancel-in-progress: true

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create or update draft release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: next
          name: Unreleased (auto-updated)
          draft: true
          allow_updates: true
          generate_release_notes: true
          make_latest: false
          fail_on_unmatched_files: false

